/**
 * 命运塔 - 196国锦标赛音乐配置系统
 * Tower of Fate - 196 Countries Tournament Music Configuration
 * 
 * 每个国家都有独特的音乐风格、乐器配置和音阶
 * Each country has unique musical style, instruments, and scale
 */

const COUNTRY_MUSIC = {
    // ==================== 亚洲 Asia (48国) ====================
    
    // 东亚 East Asia
    'CN': {
        name: '中国',
        nameEn: 'China',
        region: 'east_asia',
        instruments: ['guzheng', 'dizi', 'erhu', 'pipa'],
        style: 'chinese_traditional',
        tempo: 88,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'], // 五声音阶
        duration: 30,
        mood: 'majestic',
        description: '古筝与笛子，大气磅礴'
    },
    'JP': {
        name: '日本',
        nameEn: 'Japan',
        region: 'east_asia',
        instruments: ['shamisen', 'shakuhachi', 'taiko', 'koto'],
        style: 'japanese_traditional',
        tempo: 100,
        scale: ['E4', 'F4', 'G4', 'B4', 'C5'], // 都节音阶
        duration: 30,
        mood: 'elegant',
        description: '三味线与尺八，和风雅致'
    },
    'KR': {
        name: '韩国',
        nameEn: 'South Korea',
        region: 'east_asia',
        instruments: ['gayageum', 'daegeum', 'janggu'],
        style: 'korean_court',
        tempo: 92,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'graceful',
        description: '伽倻琴与大笒，宫廷雅乐'
    },
    'MN': {
        name: '蒙古',
        nameEn: 'Mongolia',
        region: 'east_asia',
        instruments: ['morin_khuur', 'throat_singing'],
        style: 'mongolian_pastoral',
        tempo: 76,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'expansive',
        description: '马头琴与呼麦，草原辽阔'
    },

    // 东南亚 Southeast Asia
    'TH': {
        name: '泰国',
        nameEn: 'Thailand',
        region: 'southeast_asia',
        instruments: ['ranat', 'khong_vong', 'taphon'],
        style: 'thai_classical',
        tempo: 110,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'ceremonial',
        description: '木琴与编锣，宫廷仪式'
    },
    'VN': {
        name: '越南',
        nameEn: 'Vietnam',
        region: 'southeast_asia',
        instruments: ['dan_tranh', 'dan_bau', 'trong'],
        style: 'vietnamese_folk',
        tempo: 108,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'melancholic',
        description: '独弦琴与筝，婉转悠扬'
    },
    'ID': {
        name: '印度尼西亚',
        nameEn: 'Indonesia',
        region: 'southeast_asia',
        instruments: ['gamelan', 'angklung', 'kendang'],
        style: 'gamelan',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'mystical',
        description: '甘美兰与昂格隆，神秘空灵'
    },
    'PH': {
        name: '菲律宾',
        nameEn: 'Philippines',
        region: 'southeast_asia',
        instruments: ['kulintang', 'kudyapi', 'agung'],
        style: 'philippine_ensemble',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'festive',
        description: '库林堂与吉他，热带欢庆'
    },
    'MY': {
        name: '马来西亚',
        nameEn: 'Malaysia',
        region: 'southeast_asia',
        instruments: ['gamelan', 'rebab', 'gendang'],
        style: 'malay_traditional',
        tempo: 112,
        scale: ['E4', 'F4', 'G4', 'B4', 'C5'],
        duration: 30,
        mood: 'warm',
        description: '热布与鼓，多元融合'
    },
    'SG': {
        name: '新加坡',
        nameEn: 'Singapore',
        region: 'southeast_asia',
        instruments: ['orchestra', 'fusion'],
        style: 'cosmopolitan_fusion',
        tempo: 128,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'modern',
        description: '现代融合，国际都市'
    },
    'KH': {
        name: '柬埔寨',
        nameEn: 'Cambodia',
        region: 'southeast_asia',
        instruments: ['roneat', 'skor_thom', 'sralai'],
        style: 'khmer_classical',
        tempo: 100,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'ancient',
        description: '木琴与大鼓，吴哥遗韵'
    },
    'LA': {
        name: '老挝',
        nameEn: 'Laos',
        region: 'southeast_asia',
        instruments: ['khene', 'phin', 'kong_vong'],
        style: 'lao_folk',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'serene',
        description: '芦笙与琴，宁静祥和'
    },
    'MM': {
        name: '缅甸',
        nameEn: 'Myanmar',
        region: 'southeast_asia',
        instruments: ['saung_gauk', 'pat_waing', 'kyi_waing'],
        style: 'burmese_classical',
        tempo: 90,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'spiritual',
        description: '弯琴与围鼓，佛塔梵音'
    },
    'BN': {
        name: '文莱',
        nameEn: 'Brunei',
        region: 'southeast_asia',
        instruments: ['gamelan', 'nafiri'],
        style: 'brunei_traditional',
        tempo: 98,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'noble',
        description: '甘美兰与号角，皇室尊贵'
    },
    'TL': {
        name: '东帝汶',
        nameEn: 'Timor-Leste',
        region: 'southeast_asia',
        instruments: ['gong', 'tambour', 'viola'],
        style: 'timorese_folk',
        tempo: 105,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'resilient',
        description: '铜锣与小提琴，海岛风情'
    },

    // 南亚 South Asia
    'IN': {
        name: '印度',
        nameEn: 'India',
        region: 'south_asia',
        instruments: ['sitar', 'tabla', 'bansuri', 'tanpura'],
        style: 'hindustani_classical',
        tempo: 85,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4', 'B4'], // 拉格音阶
        duration: 30,
        mood: 'spiritual',
        description: '西塔琴与塔布拉，梵音袅袅'
    },
    'PK': {
        name: '巴基斯坦',
        nameEn: 'Pakistan',
        region: 'south_asia',
        instruments: ['sitar', 'tabla', 'harmonium'],
        style: 'pakistani_qawwali',
        tempo: 110,
        scale: ['D4', 'E4', 'F4', 'G4', 'A4'],
        duration: 30,
        mood: 'devotional',
        description: '卡瓦里圣歌，虔诚激昂'
    },
    'BD': {
        name: '孟加拉国',
        nameEn: 'Bangladesh',
        region: 'south_asia',
        instruments: ['ektara', 'dotara', 'dhol'],
        style: 'bengali_folk',
        tempo: 120,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'joyful',
        description: '单弦琴与多弦琴，民歌欢快'
    },
    'LK': {
        name: '斯里兰卡',
        nameEn: 'Sri Lanka',
        region: 'south_asia',
        instruments: ['geta_beraya', 'rabana', 'thammattama'],
        style: 'sinhala_traditional',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'tropical',
        description: '鼓乐齐鸣，热带风情'
    },
    'NP': {
        name: '尼泊尔',
        nameEn: 'Nepal',
        region: 'south_asia',
        instruments: ['sarangi', 'madal', 'bansuri'],
        style: 'nepali_folk',
        tempo: 100,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'mountainous',
        description: '萨朗吉与玛达尔，山国韵律'
    },
    'BT': {
        name: '不丹',
        nameEn: 'Bhutan',
        region: 'south_asia',
        instruments: ['dramyin', 'chiwang', 'kang_dung'],
        style: 'bhutanese_religious',
        tempo: 80,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'meditative',
        description: '喇嘛号角，佛国宁静'
    },
    'MV': {
        name: '马尔代夫',
        nameEn: 'Maldives',
        region: 'south_asia',
        instruments: ['boduberu', 'thara'],
        style: 'maldivian_folk',
        tempo: 130,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'island',
        description: '鼓乐阵阵，海岛狂欢'
    },
    'AF': {
        name: '阿富汗',
        nameEn: 'Afghanistan',
        region: 'south_asia',
        instruments: ['rubab', 'dutar', 'tabla'],
        style: 'afghan_classical',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'nostalgic',
        description: '热瓦普与杜塔尔，丝路回响'
    },

    // 中亚 Central Asia
    'KZ': {
        name: '哈萨克斯坦',
        nameEn: 'Kazakhstan',
        region: 'central_asia',
        instruments: ['dombyra', 'kobyz', 'sybyzgy'],
        style: 'kazakh_nomad',
        tempo: 88,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'steppe',
        description: '冬不拉与库布孜，草原长调'
    },
    'UZ': {
        name: '乌兹别克斯坦',
        nameEn: 'Uzbekistan',
        region: 'central_asia',
        instruments: ['dutar', 'tanbur', 'doira'],
        style: 'uzbek_maqqom',
        tempo: 90,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ornate',
        description: '都塔尔与手鼓，丝绸华丽'
    },
    'KG': {
        name: '吉尔吉斯斯坦',
        nameEn: 'Kyrgyzstan',
        region: 'central_asia',
        instruments: ['komuz', 'kyiak', 'oz_komuz'],
        style: 'kyrgyz_epic',
        tempo: 85,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'epic',
        description: '考姆兹与口弦，英雄史诗'
    },
    'TJ': {
        name: '塔吉克斯坦',
        nameEn: 'Tajikistan',
        region: 'central_asia',
        instruments: ['rubab', 'ghijak', 'tabla'],
        style: 'tajik_shashmaqom',
        tempo: 92,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'classical',
        description: '六套古典，波斯遗风'
    },
    'TM': {
        name: '土库曼斯坦',
        nameEn: 'Turkmenistan',
        region: 'central_asia',
        instruments: ['dutar', 'gyjak', 'dap'],
        style: 'turkmen_bakhshy',
        tempo: 94,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'bardic',
        description: '都塔尔与吟唱，游吟诗人'
    },

    // 西亚/中东 West Asia/Middle East
    'IR': {
        name: '伊朗',
        nameEn: 'Iran',
        region: 'middle_east',
        instruments: ['tar', 'santur', 'ney', 'zarb'],
        style: 'persian_classical',
        tempo: 80,
        scale: ['D4', 'E4', 'F4', 'G4', 'A4', 'B4'], // 达斯特加赫
        duration: 30,
        mood: 'poetic',
        description: '塔尔与桑图尔，波斯诗意'
    },
    'TR': {
        name: '土耳其',
        nameEn: 'Turkey',
        region: 'middle_east',
        instruments: ['saz', 'ney', 'darbuka', 'kanun'],
        style: 'turkish_classical',
        tempo: 105,
        scale: ['E4', 'F4', 'G4', 'A4', 'B4', 'C5'],
        duration: 30,
        mood: 'whirling',
        description: '萨兹与奈伊，旋转狂舞'
    },
    'SA': {
        name: '沙特阿拉伯',
        nameEn: 'Saudi Arabia',
        region: 'middle_east',
        instruments: ['oud', 'rababah', 'mirwas'],
        style: 'arabian_peninsula',
        tempo: 100,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'desert',
        description: '乌德与拉巴哈，沙漠风情'
    },
    'IQ': {
        name: '伊拉克',
        nameEn: 'Iraq',
        region: 'middle_east',
        instruments: ['oud', 'joza', 'qanun'],
        style: 'iraqi_maqam',
        tempo: 85,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ancient',
        description: '木卡姆，两河文明'
    },
    'IL': {
        name: '以色列',
        nameEn: 'Israel',
        region: 'middle_east',
        instruments: ['oud', 'qanun', 'darbuka'],
        style: 'israeli_fusion',
        tempo: 118,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'modern',
        description: '融合传统，现代创新'
    },
    'JO': {
        name: '约旦',
        nameEn: 'Jordan',
        region: 'middle_east',
        instruments: ['rababah', 'mijwiz', 'tabl'],
        style: 'jordanian_bedouin',
        tempo: 108,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'nomadic',
        description: '贝都因音乐，游牧风情'
    },
    'LB': {
        name: '黎巴嫩',
        nameEn: 'Lebanon',
        region: 'middle_east',
        instruments: ['oud', 'derbake', 'ney'],
        style: 'lebanese_dabke',
        tempo: 130,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'festive',
        description: '达布卡舞曲，欢庆热烈'
    },
    'SY': {
        name: '叙利亚',
        nameEn: 'Syria',
        region: 'middle_east',
        instruments: ['oud', 'qanun', 'darbuka'],
        style: 'syrian_classical',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'resilient',
        description: '乌德独奏，坚韧不屈'
    },
    'YE': {
        name: '也门',
        nameEn: 'Yemen',
        region: 'middle_east',
        instruments: ['oud', 'sanaani', 'marfa'],
        style: 'yemeni_ghina',
        tempo: 90,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'melancholic',
        description: '萨那风格，古老忧伤'
    },
    'OM': {
        name: '阿曼',
        nameEn: 'Oman',
        region: 'middle_east',
        instruments: ['oud', 'khanjar', 'daf'],
        style: 'omani_sea',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'maritime',
        description: '海洋之歌，航海传统'
    },
    'AE': {
        name: '阿联酋',
        nameEn: 'United Arab Emirates',
        region: 'middle_east',
        instruments: ['oud', 'tabl', 'ney'],
        style: 'emirati_liwa',
        tempo: 115,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'noble',
        description: '利瓦鼓曲，沙漠豪情'
    },
    'QA': {
        name: '卡塔尔',
        nameEn: 'Qatar',
        region: 'middle_east',
        instruments: ['oud', 'ardha', 'tabl'],
        style: 'qatari_traditional',
        tempo: 110,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'proud',
        description: '阿达战舞，英勇自豪'
    },
    'BH': {
        name: '巴林',
        nameEn: 'Bahrain',
        region: 'middle_east',
        instruments: ['oud', 'jalsa', 'mirwas'],
        style: 'bahraini_sawt',
        tempo: 105,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'classical',
        description: '索特艺术，珍珠文化'
    },
    'KW': {
        name: '科威特',
        nameEn: 'Kuwait',
        region: 'middle_east',
        instruments: ['oud', 'sout', 'mirwas'],
        style: 'kuwaiti_sawt',
        tempo: 100,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'refined',
        description: '索特精致，海洋风情'
    },
    'GE': {
        name: '格鲁吉亚',
        nameEn: 'Georgia',
        region: 'caucasus',
        instruments: ['panduri', 'salamuri', 'chonguri'],
        style: 'georgian_polyphony',
        tempo: 88,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ancient',
        description: '三声部复调，古老独特'
    },
    'AM': {
        name: '亚美尼亚',
        nameEn: 'Armenia',
        region: 'caucasus',
        instruments: ['duduk', 'kanun', 'dhol'],
        style: 'armenian_folk',
        tempo: 78,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'soulful',
        description: '杜杜克笛，灵魂深沉'
    },
    'AZ': {
        name: '阿塞拜疆',
        nameEn: 'Azerbaijan',
        region: 'caucasus',
        instruments: ['tar', 'kamancha', 'ghaval'],
        style: 'azerbaijani_mugham',
        tempo: 85,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'expressive',
        description: '木卡姆，即兴表达'
    },

    // ==================== 欧洲 Europe (44国) ====================
    
    // 西欧 Western Europe
    'FR': {
        name: '法国',
        nameEn: 'France',
        region: 'western_europe',
        instruments: ['accordion', 'violin', 'piano'],
        style: 'french_chanson',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'romantic',
        description: '手风琴与小提琴，浪漫优雅'
    },
    'DE': {
        name: '德国',
        nameEn: 'Germany',
        region: 'western_europe',
        instruments: ['orchestra', 'organ', 'brass'],
        style: 'german_classical',
        tempo: 110,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'majestic',
        description: '交响乐与管风琴，庄严宏伟'
    },
    'UK': {
        name: '英国',
        nameEn: 'United Kingdom',
        region: 'western_europe',
        instruments: ['guitar', 'drums', 'strings'],
        style: 'british_rock',
        tempo: 128,
        scale: ['E4', 'G4', 'A4', 'B4', 'D5'],
        duration: 30,
        mood: 'energetic',
        description: '英伦摇滚，激情四射'
    },
    'IT': {
        name: '意大利',
        nameEn: 'Italy',
        region: 'western_europe',
        instruments: ['mandolin', 'violin', 'accordion'],
        style: 'italian_folk',
        tempo: 120,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'passionate',
        description: '曼陀林与小提琴，热情奔放'
    },
    'ES': {
        name: '西班牙',
        nameEn: 'Spain',
        region: 'western_europe',
        instruments: ['guitar', 'castanets', 'flamenco_box'],
        style: 'flamenco',
        tempo: 125,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'fiery',
        description: '弗拉门戈吉他，火热激情'
    },
    'PT': {
        name: '葡萄牙',
        nameEn: 'Portugal',
        region: 'western_europe',
        instruments: ['guitarra', 'fado_violin', 'portuguese_guitar'],
        style: 'fado',
        tempo: 85,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'saudade',
        description: '法多悲歌，乡愁 melancholic'
    },
    'NL': {
        name: '荷兰',
        nameEn: 'Netherlands',
        region: 'western_europe',
        instruments: ['organ', 'accordion', 'violin'],
        style: 'dutch_folk',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'cheerful',
        description: '管风琴与舞曲，欢快明朗'
    },
    'BE': {
        name: '比利时',
        nameEn: 'Belgium',
        region: 'western_europe',
        instruments: ['accordion', 'violin', 'piano'],
        style: 'belgian_folk',
        tempo: 118,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'festive',
        description: '手风琴舞曲，节日欢庆'
    },
    'CH': {
        name: '瑞士',
        nameEn: 'Switzerland',
        region: 'western_europe',
        instruments: ['alphorn', 'accordion', 'fiddle'],
        style: 'swiss_alpine',
        tempo: 108,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'alpine',
        description: '阿尔卑斯号，雪山回荡'
    },
    'AT': {
        name: '奥地利',
        nameEn: 'Austria',
        region: 'western_europe',
        instruments: ['orchestra', 'piano', 'strings'],
        style: 'vienna_classical',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'elegant',
        description: '维也纳古典，优雅精致'
    },
    'IE': {
        name: '爱尔兰',
        nameEn: 'Ireland',
        region: 'western_europe',
        instruments: ['fiddle', 'tin_whistle', 'bodhran', 'uilleann_pipes'],
        style: 'irish_celtic',
        tempo: 135,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'lively',
        description: '小提琴与风笛，凯尔特活力'
    },

    // 北欧 Northern Europe
    'SE': {
        name: '瑞典',
        nameEn: 'Sweden',
        region: 'northern_europe',
        instruments: ['nyckelharpa', 'fiddle', 'accordion'],
        style: 'swedish_folk',
        tempo: 110,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'nordic',
        description: '钥匙竖琴，北欧民谣'
    },
    'NO': {
        name: '挪威',
        nameEn: 'Norway',
        region: 'northern_europe',
        instruments: ['hardanger_fiddle', 'willow_flute', 'langeleik'],
        style: 'norwegian_folk',
        tempo: 105,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'fjord',
        description: '哈当格提琴，峡湾回响'
    },
    'DK': {
        name: '丹麦',
        nameEn: 'Denmark',
        region: 'northern_europe',
        instruments: ['accordion', 'fiddle', 'guitar'],
        style: 'danish_folk',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'hygge',
        description: '手风琴舞曲，舒适温馨'
    },
    'FI': {
        name: '芬兰',
        nameEn: 'Finland',
        region: 'northern_europe',
        instruments: ['kantele', 'violin', 'accordion'],
        style: 'finnish_folk',
        tempo: 100,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'forest',
        description: '康特勒琴，森林神秘'
    },
    'IS': {
        name: '冰岛',
        nameEn: 'Iceland',
        region: 'northern_europe',
        instruments: ['langspil', 'fiðla', 'vocals'],
        style: 'icelandic_atmospheric',
        tempo: 70,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ethereal',
        description: '氛围音乐，极光空灵'
    },

    // 东欧 Eastern Europe
    'PL': {
        name: '波兰',
        nameEn: 'Poland',
        region: 'eastern_europe',
        instruments: ['accordion', 'violin', 'clarinet'],
        style: 'polish_folk',
        tempo: 130,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'festive',
        description: '波尔卡舞曲，欢快热烈'
    },
    'UA': {
        name: '乌克兰',
        nameEn: 'Ukraine',
        region: 'eastern_europe',
        instruments: ['bandura', 'sopilka', 'tsymbaly'],
        style: 'ukrainian_folk',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'soulful',
        description: '班杜拉琴，民族深情'
    },
    'RO': {
        name: '罗马尼亚',
        nameEn: 'Romania',
        region: 'eastern_europe',
        instruments: ['cimbalom', 'violin', 'pan_flute'],
        style: 'romaninan_caf',
        tempo: 140,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'lively',
        description: '扬琴与排箫，罗姆活力'
    },
    'CZ': {
        name: '捷克',
        nameEn: 'Czech Republic',
        region: 'eastern_europe',
        instruments: ['accordion', 'clarinet', 'violin'],
        style: 'czech_polka',
        tempo: 125,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'cheerful',
        description: '波尔卡，啤酒馆欢乐'
    },
    'HU': {
        name: '匈牙利',
        nameEn: 'Hungary',
        region: 'eastern_europe',
        instruments: ['cimbalom', 'violin', 'clarinet'],
        style: 'hungarian_csardas',
        tempo: 135,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'passionate',
        description: '查尔达什舞曲，吉普赛激情'
    },
    'SK': {
        name: '斯洛伐克',
        nameEn: 'Slovakia',
        region: 'eastern_europe',
        instruments: ['fujara', 'violin', 'accordion'],
        style: 'slovak_folk',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'mountain',
        description: '富加拉笛，塔特拉山歌'
    },
    'BY': {
        name: '白俄罗斯',
        nameEn: 'Belarus',
        region: 'eastern_europe',
        instruments: ['tsymbaly', 'duda', 'fiddle'],
        style: 'belarusian_folk',
        tempo: 110,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'nostalgic',
        description: '风笛与扬琴，乡愁怀旧'
    },
    'MD': {
        name: '摩尔多瓦',
        nameEn: 'Moldova',
        region: 'eastern_europe',
        instruments: ['nai', 'violin', 'cimbalom'],
        style: 'moldovan_hora',
        tempo: 118,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'romantic',
        description: '霍拉舞曲，多瑙河浪漫'
    },
    'LT': {
        name: '立陶宛',
        nameEn: 'Lithuania',
        region: 'eastern_europe',
        instruments: ['kankles', 'skuduciai', 'fiddle'],
        style: 'lithuanian_sutartines',
        tempo: 105,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ancient',
        description: '复调民歌，波罗的海古风'
    },
    'LV': {
        name: '拉脱维亚',
        nameEn: 'Latvia',
        region: 'eastern_europe',
        instruments: ['kokle', 'bagpipes', 'drums'],
        style: 'latvian_folk',
        tempo: 108,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'nature',
        description: '科克勒琴，自然崇拜'
    },
    'EE': {
        name: '爱沙尼亚',
        nameEn: 'Estonia',
        region: 'eastern_europe',
        instruments: ['kannel', 'torupill', 'fiddle'],
        style: 'estonian_regilaul',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'runic',
        description: '如尼歌谣，古调吟唱'
    },

    // 南欧/巴尔干 Southern Europe/Balkans
    'GR': {
        name: '希腊',
        nameEn: 'Greece',
        region: 'southern_europe',
        instruments: ['bouzouki', 'clarinet', 'violin'],
        style: 'greek_rebetiko',
        tempo: 110,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'passionate',
        description: '布祖基琴，雷贝蒂科'
    },
    'RS': {
        name: '塞尔维亚',
        nameEn: 'Serbia',
        region: 'balkans',
        instruments: ['gusle', 'frula', 'accordion'],
        style: 'serbian_kolo',
        tempo: 140,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'energetic',
        description: '古斯列琴，科洛圆圈舞'
    },
    'HR': {
        name: '克罗地亚',
        nameEn: 'Croatia',
        region: 'balkans',
        instruments: ['tamburitza', 'accordion', 'violin'],
        style: 'croatian_tamburitza',
        tempo: 125,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'coastal',
        description: '坦布里扎，亚得里亚海岸'
    },
    'BG': {
        name: '保加利亚',
        nameEn: 'Bulgaria',
        region: 'balkans',
        instruments: ['gaida', 'kaval', 'tupan'],
        style: 'bulgarian_folk',
        tempo: 150,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'complex',
        description: '风笛与长笛，不对称节拍'
    },
    'AL': {
        name: '阿尔巴尼亚',
        nameEn: 'Albania',
        region: 'balkans',
        instruments: ['cifteli', 'lahuta', 'def'],
        style: 'albanian_iso_polyphony',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'mountain',
        description: '复调合唱，山鹰之歌'
    },
    'SI': {
        name: '斯洛文尼亚',
        nameEn: 'Slovenia',
        region: 'balkans',
        instruments: ['accordion', 'violin', 'clarinet'],
        style: 'slovenian_folk',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'alpine',
        description: '阿尔卑斯舞曲，山地清新'
    },
    'BA': {
        name: '波黑',
        nameEn: 'Bosnia and Herzegovina',
        region: 'balkans',
        instruments: ['sevdah', 'accordion', 'saz'],
        style: 'bosnian_sevdalinka',
        tempo: 85,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'melancholic',
        description: '塞夫达林卡，巴尔干忧郁'
    },
    'MK': {
        name: '北马其顿',
        nameEn: 'North Macedonia',
        region: 'balkans',
        instruments: ['zurla', 'tapan', 'kaval'],
        style: 'macedonian_oro',
        tempo: 135,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'rhythmic',
        description: '奥罗舞曲，山地节奏'
    },
    'ME': {
        name: '黑山',
        nameEn: 'Montenegro',
        region: 'balkans',
        instruments: ['gusle', 'violin', 'accordion'],
        style: 'montenegrin_gusle',
        tempo: 90,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'epic',
        description: '英雄史诗，黑山豪迈'
    },
    'XK': {
        name: '科索沃',
        nameEn: 'Kosovo',
        region: 'balkans',
        instruments: ['saz', 'violin', 'darbuka'],
        style: 'kosovar_albanian',
        tempo: 110,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'resilient',
        description: '阿尔巴尼亚风，坚韧不屈'
    },

    // ==================== 北美洲 North America (23国) ====================
    'US': {
        name: '美国',
        nameEn: 'United States',
        region: 'north_america',
        instruments: ['electric_guitar', 'drums', 'bass'],
        style: 'american_rock',
        tempo: 135,
        scale: ['E4', 'G4', 'A4', 'B4', 'D5'],
        duration: 30,
        mood: 'energetic',
        description: '电吉他摇滚，自由精神'
    },
    'CA': {
        name: '加拿大',
        nameEn: 'Canada',
        region: 'north_america',
        instruments: ['acoustic_guitar', 'fiddle', 'accordion'],
        style: 'canadian_folk',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'northern',
        description: '民谣与提琴，北方广阔'
    },
    'MX': {
        name: '墨西哥',
        nameEn: 'Mexico',
        region: 'north_america',
        instruments: ['guitarron', 'vihuela', 'trumpet'],
        style: 'mariachi',
        tempo: 130,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'fiesta',
        description: '马里亚奇乐队，墨西哥狂欢'
    },
    'GT': {
        name: '危地马拉',
        nameEn: 'Guatemala',
        region: 'central_america',
        instruments: ['marimba', 'guitar', 'drums'],
        style: 'guatemalan_marimba',
        tempo: 120,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'colorful',
        description: '马林巴木琴，玛雅色彩'
    },
    'BZ': {
        name: '伯利兹',
        nameEn: 'Belize',
        region: 'central_america',
        instruments: ['garifuna_drums', 'turtle_shells', 'guitar'],
        style: 'garifuna_punta',
        tempo: 140,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'tropical',
        description: '加里富纳鼓，加勒比热带'
    },
    'SV': {
        name: '萨尔瓦多',
        nameEn: 'El Salvador',
        region: 'central_america',
        instruments: ['marimba', 'guitar', 'xylophone'],
        style: 'salvadoran_xuc',
        tempo: 125,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'festive',
        description: '苏克舞曲，节日欢庆'
    },
    'HN': {
        name: '洪都拉斯',
        nameEn: 'Honduras',
        region: 'central_america',
        instruments: ['marimba', 'guitar', 'percussion'],
        style: 'honduran_punta',
        tempo: 135,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'lively',
        description: '蓬塔舞曲，加勒比活力'
    },
    'NI': {
        name: '尼加拉瓜',
        nameEn: 'Nicaragua',
        region: 'central_america',
        instruments: ['marimba', 'guitar', 'percussion'],
        style: 'nicaraguan_palo_de_mayo',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'celebratory',
        description: '五月柱舞曲，海岸庆典'
    },
    'CR': {
        name: '哥斯达黎加',
        nameEn: 'Costa Rica',
        region: 'central_america',
        instruments: ['marimba', 'guitar', 'accordion'],
        style: 'costa_rican_punto_guanacasteco',
        tempo: 125,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'pura_vida',
        description: '关纳卡斯特科，纯净生活'
    },
    'PA': {
        name: '巴拿马',
        nameEn: 'Panama',
        region: 'central_america',
        instruments: ['mejorana', 'accordion', 'tamborito'],
        style: 'panamanian_tamborito',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'soulful',
        description: '小鼓与手风琴，民族深情'
    },
    'CU': {
        name: '古巴',
        nameEn: 'Cuba',
        region: 'caribbean',
        instruments: ['congas', 'bongos', 'trumpet', 'piano'],
        style: 'cuban_salsa',
        tempo: 145,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'rhythmic',
        description: '萨尔萨与康加，古巴律动'
    },
    'JM': {
        name: '牙买加',
        nameEn: 'Jamaica',
        region: 'caribbean',
        instruments: ['bass', 'guitar', 'drums', 'keyboard'],
        style: 'jamaican_reggae',
        tempo: 90,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'relaxed',
        description: '雷鬼音乐，牙买加 chill'
    },
    'HT': {
        name: '海地',
        nameEn: 'Haiti',
        region: 'caribbean',
        instruments: ['drums', 'rara', 'vaksin'],
        style: 'haitian_compas',
        tempo: 130,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'festive',
        description: '康帕斯舞曲，伏都狂欢'
    },
    'DO': {
        name: '多米尼加',
        nameEn: 'Dominican Republic',
        region: 'caribbean',
        instruments: ['accordion', 'güira', 'tambora'],
        style: 'dominican_merengue',
        tempo: 150,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'energetic',
        description: '梅伦格舞曲，热情奔放'
    },
    'TT': {
        name: '特立尼达和多巴哥',
        nameEn: 'Trinidad and Tobago',
        region: 'caribbean',
        instruments: ['steelpan', 'drums', 'brass'],
        style: 'trinidadian_calypso',
        tempo: 140,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'carnival',
        description: '钢鼓与卡利普索，加勒比狂欢'
    },
    'BS': {
        name: '巴哈马',
        nameEn: 'Bahamas',
        region: 'caribbean',
        instruments: ['goombay', 'saw', 'drums'],
        style: 'bahamian_junkanoo',
        tempo: 145,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'carnival',
        description: ' junkanoo 鼓，巴哈马节庆'
    },
    'BB': {
        name: '巴巴多斯',
        nameEn: 'Barbados',
        region: 'caribbean',
        instruments: ['spouge', 'drums', 'guitar'],
        style: 'barbadian_spouge',
        tempo: 125,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'tropical',
        description: '斯波格节奏，岛屿风情'
    },
    'AG': {
        name: '安提瓜和巴布达',
        nameEn: 'Antigua and Barbuda',
        region: 'caribbean',
        instruments: ['steelpan', 'banjo', 'drums'],
        style: 'antiguan_calypso',
        tempo: 135,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'beach',
        description: '卡利普索，海滩风情'
    },
    'DM': {
        name: '多米尼克',
        nameEn: 'Dominica',
        region: 'caribbean',
        instruments: ['bouyon', 'accordion', 'drums'],
        style: 'dominican_bouyon',
        tempo: 130,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'island',
        description: '布永节奏，自然岛屿'
    },
    'LC': {
        name: '圣卢西亚',
        nameEn: 'Saint Lucia',
        region: 'caribbean',
        instruments: ['kwadril', 'accordion', 'drums'],
        style: 'saint_lucian_kwadril',
        tempo: 120,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'heritage',
        description: '方块舞，克里奥尔遗产'
    },
    'VC': {
        name: '圣文森特和格林纳丁斯',
        nameEn: 'Saint Vincent and the Grenadines',
        region: 'caribbean',
        instruments: ['big_drum', 'steelpan', 'violin'],
        style: 'vincentian_big_drum',
        tempo: 125,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'traditional',
        description: '大鼓节奏，传统庆典'
    },
    'GD': {
        name: '格林纳达',
        nameEn: 'Grenada',
        region: 'caribbean',
        instruments: ['jab_jab', 'drums', 'brass'],
        style: 'grenadian_spicemas',
        tempo: 140,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'spice',
        description: ' Spice Mas，香料狂欢'
    },
    'KN': {
        name: '圣基茨和尼维斯',
        nameEn: 'Saint Kitts and Nevis',
        region: 'caribbean',
        instruments: ['moko_jumbie', 'drums', 'brass'],
        style: 'kittitian_carnival',
        tempo: 130,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'festive',
        description: '狂欢节，庆祝自由'
    },

    // ==================== 南美洲 South America (12国) ====================
    'BR': {
        name: '巴西',
        nameEn: 'Brazil',
        region: 'south_america',
        instruments: ['surdo', 'tamborim', 'cavaquinho', 'bandolim'],
        style: 'brazilian_samba',
        tempo: 140,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'carnival',
        description: '桑巴鼓乐，巴西狂欢'
    },
    'AR': {
        name: '阿根廷',
        nameEn: 'Argentina',
        region: 'south_america',
        instruments: ['bandoneon', 'guitar', 'violin'],
        style: 'argentinian_tango',
        tempo: 120,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'passionate',
        description: '班多钮探戈，布宜诺斯艾利斯激情'
    },
    'CO': {
        name: '哥伦比亚',
        nameEn: 'Colombia',
        region: 'south_america',
        instruments: ['accordion', 'guitar', 'guacharaca'],
        style: 'colombian_cumbia',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'joyful',
        description: '昆比亚舞曲，加勒比海岸'
    },
    'PE': {
        name: '秘鲁',
        nameEn: 'Peru',
        region: 'south_america',
        instruments: ['charango', 'quena', 'zampoña'],
        style: 'peruvian_andean',
        tempo: 100,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'ancestral',
        description: '查朗戈与盖那笛，安第斯山脉'
    },
    'CL': {
        name: '智利',
        nameEn: 'Chile',
        region: 'south_america',
        instruments: ['guitar', 'charango', 'bombo'],
        style: 'chilean_cueca',
        tempo: 125,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'national',
        description: '奎卡舞曲，国舞风采'
    },
    'VE': {
        name: '委内瑞拉',
        nameEn: 'Venezuela',
        region: 'south_america',
        instruments: ['cuatro', 'maracas', 'harp'],
        style: 'venezuelan_joropo',
        tempo: 135,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'llanero',
        description: '霍罗波舞曲，平原风情'
    },
    'EC': {
        name: '厄瓜多尔',
        nameEn: 'Ecuador',
        region: 'south_america',
        instruments: ['rondador', 'guitar', 'bomba'],
        style: 'ecuadorian_san_juanito',
        tempo: 115,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'andean',
        description: '圣胡安尼托，安第斯高地'
    },
    'BO': {
        name: '玻利维亚',
        nameEn: 'Bolivia',
        region: 'south_america',
        instruments: ['charango', 'siku', 'bombo'],
        style: 'bolivian_sicuri',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'altitude',
        description: '西库里排箫，高原神韵'
    },
    'PY': {
        name: '巴拉圭',
        nameEn: 'Paraguay',
        region: 'south_america',
        instruments: ['harp', 'guitar', 'guitarra_paraguaya'],
        style: 'paraguayan_guarania',
        tempo: 90,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'melancholic',
        description: '瓜拉尼竖琴，忧郁深沉'
    },
    'UY': {
        name: '乌拉圭',
        nameEn: 'Uruguay',
        region: 'south_america',
        instruments: ['bandoneon', 'guitar', 'percussion'],
        style: 'uruguayan_murga',
        tempo: 125,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'carnival',
        description: '穆尔加合唱，狂欢节'
    },
    'GY': {
        name: '圭亚那',
        nameEn: 'Guyana',
        region: 'south_america',
        instruments: ['steelpan', 'chutney', 'drums'],
        style: 'guyanese_mashramani',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'celebration',
        description: '马什拉马尼，丰收庆典'
    },
    'SR': {
        name: '苏里南',
        nameEn: 'Suriname',
        region: 'south_america',
        instruments: ['kaseko', 'drums', 'brass'],
        style: 'surinamese_kaseko',
        tempo: 135,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'creole',
        description: '卡塞科鼓乐，克里奥尔风'
    },

    // ==================== 非洲 Africa (54国) ====================
    
    // 北非 North Africa
    'EG': {
        name: '埃及',
        nameEn: 'Egypt',
        region: 'north_africa',
        instruments: ['oud', 'qanun', 'ney', 'tabla'],
        style: 'egyptian_classical',
        tempo: 100,
        scale: ['D4', 'E4', 'F4', 'G4', 'A4'],
        duration: 30,
        mood: 'ancient',
        description: '阿拉伯古典，尼罗河文明'
    },
    'MA': {
        name: '摩洛哥',
        nameEn: 'Morocco',
        region: 'north_africa',
        instruments: ['oud', 'gnawa_bass', 'qraqeb'],
        style: 'moroccan_gnawa',
        tempo: 110,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'trance',
        description: '格纳瓦音乐，撒哈拉迷幻'
    },
    'DZ': {
        name: '阿尔及利亚',
        nameEn: 'Algeria',
        region: 'north_africa',
        instruments: ['mandole', 'gasba', 'bendir'],
        style: 'algerian_rai',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'rebellious',
        description: '拉伊音乐，叛逆之声'
    },
    'TN': {
        name: '突尼斯',
        nameEn: 'Tunisia',
        region: 'north_africa',
        instruments: ['oud', 'mezwed', 'darbuka'],
        style: 'tunisian_malouf',
        tempo: 105,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'classical',
        description: '马卢夫古典，安达卢西亚遗风'
    },
    'LY': {
        name: '利比亚',
        nameEn: 'Libya',
        region: 'north_africa',
        instruments: ['oud', 'zukra', 'tabl'],
        style: 'libyan_folk',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'desert',
        description: '祖克拉号，沙漠回响'
    },
    'SD': {
        name: '苏丹',
        nameEn: 'Sudan',
        region: 'north_africa',
        instruments: ['oud', 'tambour', 'drums'],
        style: 'sudanese_haqiba',
        tempo: 100,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'nile',
        description: '哈吉巴风格，尼罗河悠长'
    },
    'MR': {
        name: '毛里塔尼亚',
        nameEn: 'Mauritania',
        region: 'north_africa',
        instruments: ['tidinit', 'ardine', 'tbal'],
        style: 'mauritanian_griots',
        tempo: 90,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'griot',
        description: '格里奥特音乐，沙漠史诗'
    },

    // 西非 West Africa
    'NG': {
        name: '尼日利亚',
        nameEn: 'Nigeria',
        region: 'west_africa',
        instruments: ['talking_drum', 'dundun', 'bata', 'shekere'],
        style: 'nigerian_afrobeat',
        tempo: 125,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'energetic',
        description: '会说话的鼓，非洲节拍'
    },
    'GH': {
        name: '加纳',
        nameEn: 'Ghana',
        region: 'west_africa',
        instruments: ['gombe', 'dondo', 'seprewa'],
        style: 'ghanaian_highlife',
        tempo: 120,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'joyful',
        description: '高生活音乐，黄金海岸'
    },
    'CI': {
        name: '科特迪瓦',
        nameEn: "Côte d'Ivoire",
        region: 'west_africa',
        instruments: ['zouglou', 'coupe_decale', 'drums'],
        style: 'ivorian_zouglou',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'youth',
        description: '祖格鲁音乐，青年之声'
    },
    'ML': {
        name: '马里',
        nameEn: 'Mali',
        region: 'west_africa',
        instruments: ['kora', 'balafon', 'ngoni'],
        style: 'malian_griot',
        tempo: 95,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'ancient',
        description: '科拉琴与巴拉风，格里奥特史诗'
    },
    'SN': {
        name: '塞内加尔',
        nameEn: 'Senegal',
        region: 'west_africa',
        instruments: ['kora', 'sabar', 'tama'],
        style: 'senegalese_mbalax',
        tempo: 135,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'rhythmic',
        description: '姆巴拉克斯，萨巴尔鼓'
    },
    'BF': {
        name: '布基纳法索',
        nameEn: 'Burkina Faso',
        region: 'west_africa',
        instruments: ['balafon', 'djembe', 'nanga'],
        style: 'burkinabe_mossi',
        tempo: 110,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ancestral',
        description: '莫西传统，巴拉风韵律'
    },
    'GN': {
        name: '几内亚',
        nameEn: 'Guinea',
        region: 'west_africa',
        instruments: ['djembe', 'bala', 'kora'],
        style: 'guinean_djembe',
        tempo: 140,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'powerful',
        description: '金贝鼓大师，节奏之魂'
    },
    'SL': {
        name: '塞拉利昂',
        nameEn: 'Sierra Leone',
        region: 'west_africa',
        instruments: ['bubu', 'drums', 'strings'],
        style: 'sierra_leonean_bubu',
        tempo: 125,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'street',
        description: '布布音乐，街头狂欢'
    },
    'LR': {
        name: '利比里亚',
        nameEn: 'Liberia',
        region: 'west_africa',
        instruments: ['drums', 'sasa', 'giga'],
        style: 'liberian_gio',
        tempo: 115,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'traditional',
        description: '吉奥传统，丛林节奏'
    },
    'GM': {
        name: '冈比亚',
        nameEn: 'Gambia',
        region: 'west_africa',
        instruments: ['kora', 'balafon', 'djembe'],
        style: 'gambian_mandinka',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'storytelling',
        description: '曼丁卡史诗，讲故事传统'
    },
    'TG': {
        name: '多哥',
        nameEn: 'Togo',
        region: 'west_africa',
        instruments: ['akye', 'drums', 'gong'],
        style: 'togolese_ewe',
        tempo: 120,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'polyrhythm',
        description: '埃维复节奏，复杂精妙'
    },
    'BJ': {
        name: '贝宁',
        nameEn: 'Benin',
        region: 'west_africa',
        instruments: ['agidigbo', 'drums', 'percussion'],
        style: 'beninese_vodoun',
        tempo: 110,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'spiritual',
        description: '伏都音乐，精神仪式'
    },
    'NE': {
        name: '尼日尔',
        nameEn: 'Niger',
        region: 'west_africa',
        instruments: ['griot', 'guitar', 'drums'],
        style: 'nigerien_tuareg',
        tempo: 105,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'desert_blues',
        description: '图阿雷格蓝调，沙漠摇滚'
    },
    'CV': {
        name: '佛得角',
        nameEn: 'Cape Verde',
        region: 'west_africa',
        instruments: ['cavaquinho', 'accordion', 'violin'],
        style: 'cape_verdean_morna',
        tempo: 85,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'saudade',
        description: '莫尔纳悲歌，乡愁 melancholic'
    },

    // 东非 East Africa
    'ET': {
        name: '埃塞俄比亚',
        nameEn: 'Ethiopia',
        region: 'east_africa',
        instruments: ['masenqo', 'krar', 'washint'],
        style: 'ethiopian_jazz',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'unique',
        description: '埃塞俄比亚爵士，独特音阶'
    },
    'KE': {
        name: '肯尼亚',
        nameEn: 'Kenya',
        region: 'east_africa',
        instruments: ['benga', 'orutu', 'nyatiti'],
        style: 'kenyan_benga',
        tempo: 125,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'upbeat',
        description: '本加音乐，卢奥节奏'
    },
    'TZ': {
        name: '坦桑尼亚',
        nameEn: 'Tanzania',
        region: 'east_africa',
        instruments: ['taarab', 'ngoma', 'marimba'],
        style: 'tanzanian_taarab',
        tempo: 110,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'swahili',
        description: '塔拉布音乐，斯瓦希里海岸'
    },
    'UG': {
        name: '乌干达',
        nameEn: 'Uganda',
        region: 'east_africa',
        instruments: ['adungu', 'engoma', 'amadinda'],
        style: 'ugandan_kadongo_kamu',
        tempo: 120,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'royal',
        description: '卡东戈卡穆，皇室木琴'
    },
    'RW': {
        name: '卢旺达',
        nameEn: 'Rwanda',
        region: 'east_africa',
        instruments: ['inyange', 'umuduri', 'ikembe'],
        style: 'rwandan_intore',
        tempo: 130,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'warrior',
        description: '因托雷战舞，牛羚鼓'
    },
    'BI': {
        name: '布隆迪',
        nameEn: 'Burundi',
        region: 'east_africa',
        instruments: ['inkiranya', 'ikembe', 'drums'],
        style: 'burundian_drummers',
        tempo: 145,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'powerful',
        description: '皇家鼓手，神圣鼓乐'
    },
    'SO': {
        name: '索马里',
        nameEn: 'Somalia',
        region: 'east_africa',
        instruments: ['oud', 'batar', 'drums'],
        style: 'somali_qaraami',
        tempo: 105,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'poetic',
        description: '卡拉米音乐，游牧诗歌'
    },
    'DJ': {
        name: '吉布提',
        nameEn: 'Djibouti',
        region: 'east_africa',
        instruments: ['oud', 'tanbura', 'drums'],
        style: 'djiboutian_somali_afar',
        tempo: 100,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'fusion',
        description: '索马里阿法尔融合'
    },
    'ER': {
        name: '厄立特里亚',
        nameEn: 'Eritrea',
        region: 'east_africa',
        instruments: ['krar', 'wata', 'drums'],
        style: 'eritrean_tigrinya',
        tempo: 110,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'patriotic',
        description: '提格里尼亚，独立精神'
    },
    'MW': {
        name: '马拉维',
        nameEn: 'Malawi',
        region: 'east_africa',
        instruments: ['banjo', 'drums', 'marimba'],
        style: 'malawian_gule_wamkulu',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'ceremonial',
        description: '大舞仪式，面具舞蹈'
    },
    'MZ': {
        name: '莫桑比克',
        nameEn: 'Mozambique',
        region: 'east_africa',
        instruments: ['timila', 'mbira', 'drums'],
        style: 'mozambican_marrabenta',
        tempo: 135,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'festive',
        description: '马拉本塔，葡萄牙融合'
    },
    'ZM': {
        name: '赞比亚',
        nameEn: 'Zambia',
        region: 'east_africa',
        instruments: ['kalimba', 'ngoma', 'xylophone'],
        style: 'zambian_kalindula',
        tempo: 120,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'electric',
        description: '卡林杜拉，电吉他传统'
    },
    'ZW': {
        name: '津巴布韦',
        nameEn: 'Zimbabwe',
        region: 'east_africa',
        instruments: ['mbira', 'hosho', 'marimba'],
        style: 'zimbabwean_chimurenga',
        tempo: 110,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'spiritual',
        description: '姆比拉拇指琴，绍纳灵歌'
    },

    // 中非 Central Africa
    'CD': {
        name: '刚果(金)',
        nameEn: 'Democratic Republic of Congo',
        region: 'central_africa',
        instruments: ['likembe', 'drums', 'guitar'],
        style: 'congolese_rumba',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'dance',
        description: '刚果伦巴，舞蹈之王'
    },
    'CG': {
        name: '刚果(布)',
        nameEn: 'Republic of Congo',
        region: 'central_africa',
        instruments: ['likembe', 'drums', 'ballet'],
        style: 'congolese_soukous',
        tempo: 140,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'energetic',
        description: '苏库斯，快舞节奏'
    },
    'GA': {
        name: '加蓬',
        nameEn: 'Gabon',
        region: 'central_africa',
        instruments: ['mvet', 'ngombi', 'drums'],
        style: 'gabonese_bwiti',
        tempo: 95,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'sacred',
        description: '布维提仪式，神圣竖琴'
    },
    'CM': {
        name: '喀麦隆',
        nameEn: 'Cameroon',
        region: 'central_africa',
        instruments: ['mvet', 'balafon', 'drums'],
        style: 'cameroonian_makossa',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'dance',
        description: '马科萨舞曲，摇摆喀麦隆'
    },
    'TD': {
        name: '乍得',
        nameEn: 'Chad',
        region: 'central_africa',
        instruments: ['kinde', 'drums', 'strings'],
        style: 'chadian_sahel',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'savanna',
        description: '萨赫尔音乐，草原之声'
    },
    'CF': {
        name: '中非',
        nameEn: 'Central African Republic',
        region: 'central_africa',
        instruments: ['drums', 'balafon', 'harp'],
        style: 'car_aka',
        tempo: 105,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'forest',
        description: '阿卡俾格米，雨林复调'
    },
    'GQ': {
        name: '赤道几内亚',
        nameEn: 'Equatorial Guinea',
        region: 'central_africa',
        instruments: ['drums', 'bata', 'guitar'],
        style: 'equatoguinean_anne',
        tempo: 115,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'celebration',
        description: '安妮舞曲，大陆岛屿融合'
    },
    'ST': {
        name: '圣多美和普林西比',
        nameEn: 'São Tomé and Príncipe',
        region: 'central_africa',
        instruments: ['guitars', 'drums', 'accordion'],
        style: 'sao_tomean_danse_congo',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'tropical',
        description: '刚果舞，葡萄牙非洲'
    },

    // 南非 Southern Africa
    'ZA': {
        name: '南非',
        nameEn: 'South Africa',
        region: 'southern_africa',
        instruments: ['mbira', 'drums', 'brass', 'vuvuzela'],
        style: 'south_african_kwaito',
        tempo: 120,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'township',
        description: '库威托舞曲，索韦托活力'
    },
    'NA': {
        name: '纳米比亚',
        nameEn: 'Namibia',
        region: 'southern_africa',
        instruments: ['drums', 'guitar', 'traditional'],
        style: 'namibian_oshiwambo',
        tempo: 110,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'desert',
        description: '奥希万博，沙漠节奏'
    },
    'BW': {
        name: '博茨瓦纳',
        nameEn: 'Botswana',
        region: 'southern_africa',
        instruments: ['drums', 'bojale', 'guitar'],
        style: 'botswana_folk',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'peaceful',
        description: '博贾莱音乐，沙漠宁静'
    },
    'SZ': {
        name: '斯威士兰',
        nameEn: 'Eswatini',
        region: 'southern_africa',
        instruments: ['sibhaca', 'drums', 'rattles'],
        style: 'swazi_sibhaca',
        tempo: 140,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'warrior',
        description: '西巴卡战舞，芦苇节'
    },
    'LS': {
        name: '莱索托',
        nameEn: 'Lesotho',
        region: 'southern_africa',
        instruments: ['lesiba', 'thomo', 'drums'],
        style: 'basotho_famo',
        tempo: 115,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'mountain',
        description: '法莫音乐，高山王国'
    },
    'MG': {
        name: '马达加斯加',
        nameEn: 'Madagascar',
        region: 'southern_africa',
        instruments: ['valiha', 'marovany', 'kabosy'],
        style: 'malagasy_salegy',
        tempo: 135,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'island',
        description: '瓦利哈竹琴，萨莱吉舞曲'
    },
    'MU': {
        name: '毛里求斯',
        nameEn: 'Mauritius',
        region: 'southern_africa',
        instruments: ['ravanne', 'maravanne', 'triangle'],
        style: 'mauritian_sega',
        tempo: 130,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'creole',
        description: '塞加音乐，克里奥尔融合'
    },
    'KM': {
        name: '科摩罗',
        nameEn: 'Comoros',
        region: 'southern_africa',
        instruments: ['gambusi', 'ndzendze', 'drums'],
        style: 'comorian_twarab',
        tempo: 105,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'swahili',
        description: '图瓦拉布，斯瓦希里阿拉伯'
    },
    'SC': {
        name: '塞舌尔',
        nameEn: 'Seychelles',
        region: 'southern_africa',
        instruments: ['moutya', 'tambour', 'triangle'],
        style: 'seychellois_moutya',
        tempo: 120,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'tropical',
        description: '穆蒂亚鼓，非洲克里奥尔'
    },

    // ==================== 大洋洲 Oceania (14国) ====================
    'AU': {
        name: '澳大利亚',
        nameEn: 'Australia',
        region: 'oceania',
        instruments: ['didgeridoo', 'clapsticks', 'guitar'],
        style: 'australian_rock',
        tempo: 125,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'outback',
        description: '迪吉里杜管，原住民摇滚'
    },
    'NZ': {
        name: '新西兰',
        nameEn: 'New Zealand',
        region: 'oceania',
        instruments: ['taonga_puoro', 'guitar', 'drums'],
        style: 'maori_waiata',
        tempo: 100,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'cultural',
        description: '毛利乐声，长哈仪式'
    },
    'PG': {
        name: '巴布亚新几内亚',
        nameEn: 'Papua New Guinea',
        region: 'oceania',
        instruments: ['kundu', 'garamut', 'singsing'],
        style: 'png_singsing',
        tempo: 115,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'tribal',
        description: ' singsing 庆典，部落风情'
    },
    'FJ': {
        name: '斐济',
        nameEn: 'Fiji',
        region: 'oceania',
        instruments: ['lali', 'meke', 'guitar'],
        style: 'fijian_meke',
        tempo: 110,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'island',
        description: '梅克歌舞，太平洋风情'
    },
    'SB': {
        name: '所罗门群岛',
        nameEn: 'Solomon Islands',
        region: 'oceania',
        instruments: ['panpipes', 'bamboo', 'drums'],
        style: 'solomon_islands_bamboo',
        tempo: 105,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'melanesian',
        description: '竹管排箫，美拉尼西亚'
    },
    'VU': {
        name: '瓦努阿图',
        nameEn: 'Vanuatu',
        region: 'oceania',
        instruments: ['tam-tam', 'slit_drum', 'panpipes'],
        style: 'vanuatu_water_music',
        tempo: 100,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'water',
        description: '水音乐， slit drum 独特'
    },
    'WS': {
        name: '萨摩亚',
        nameEn: 'Samoa',
        region: 'oceania',
        instruments: ['pate', 'fala', 'vocals'],
        style: 'samoan_siva',
        tempo: 95,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'pacific',
        description: '西瓦舞蹈，波利尼西亚'
    },
    'TO': {
        name: '汤加',
        nameEn: 'Tonga',
        region: 'oceania',
        instruments: ['nose_flute', 'lali', 'vocals'],
        style: 'tongan_lakalaka',
        tempo: 90,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'royal',
        description: '拉卡拉卡，皇室歌舞'
    },
    'KI': {
        name: '基里巴斯',
        nameEn: 'Kiribati',
        region: 'oceania',
        instruments: ['ukulele', 'vocals', 'clapping'],
        style: 'kiribati_standing_dance',
        tempo: 110,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'island',
        description: '站立舞蹈，赤道岛国'
    },
    'TV': {
        name: '图瓦卢',
        nameEn: 'Tuvalu',
        region: 'oceania',
        instruments: ['fatele', 'drums', 'vocals'],
        style: 'tuvaluan_fatele',
        tempo: 130,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'community',
        description: '法特勒舞蹈，社区欢庆'
    },
    'NR': {
        name: '瑙鲁',
        nameEn: 'Nauru',
        region: 'oceania',
        instruments: ['drums', 'vocals', 'clapping'],
        style: 'nauran_dance',
        tempo: 115,
        scale: ['D4', 'E4', 'G4', 'A4', 'B4'],
        duration: 30,
        mood: 'island',
        description: '岛国传统，磷酸盐之歌'
    },
    'PW': {
        name: '帕劳',
        nameEn: 'Palau',
        region: 'oceania',
        instruments: ['kuling', 'bamboo', 'shells'],
        style: 'palauan_keskes',
        tempo: 100,
        scale: ['G4', 'A4', 'B4', 'D5', 'E5'],
        duration: 30,
        mood: 'micronesian',
        description: '克斯克斯，密克罗尼西亚'
    },
    'MH': {
        name: '马绍尔群岛',
        nameEn: 'Marshall Islands',
        region: 'oceania',
        instruments: ['drum', 'ukulele', 'vocals'],
        style: 'marshallese_jebwa',
        tempo: 105,
        scale: ['C4', 'D4', 'E4', 'G4', 'A4'],
        duration: 30,
        mood: 'navigation',
        description: '杰布瓦，航海传统'
    },
    'FM': {
        name: '密克罗尼西亚联邦',
        nameEn: 'Micronesia',
        region: 'oceania',
        instruments: ['drum', 'stick', 'shells'],
        style: 'micronesian_dance',
        tempo: 95,
        scale: ['F4', 'G4', 'A4', 'C5', 'D5'],
        duration: 30,
        mood: 'traditional',
        description: '密克罗尼西亚，岛链文化'
    }
};

// 按地区分类的国家代码
const REGION_GROUPS = {
    east_asia: ['CN', 'JP', 'KR', 'MN'],
    southeast_asia: ['TH', 'VN', 'ID', 'PH', 'MY', 'SG', 'KH', 'LA', 'MM', 'BN', 'TL'],
    south_asia: ['IN', 'PK', 'BD', 'LK', 'NP', 'BT', 'MV', 'AF'],
    central_asia: ['KZ', 'UZ', 'KG', 'TJ', 'TM'],
    middle_east: ['IR', 'TR', 'SA', 'IQ', 'IL', 'JO', 'LB', 'SY', 'YE', 'OM', 'AE', 'QA', 'BH', 'KW'],
    caucasus: ['GE', 'AM', 'AZ'],
    western_europe: ['FR', 'DE', 'UK', 'IT', 'ES', 'PT', 'NL', 'BE', 'CH', 'AT', 'IE'],
    northern_europe: ['SE', 'NO', 'DK', 'FI', 'IS'],
    eastern_europe: ['PL', 'UA', 'RO', 'CZ', 'HU', 'SK', 'BY', 'MD', 'LT', 'LV', 'EE'],
    southern_europe: ['GR'],
    balkans: ['RS', 'HR', 'BG', 'AL', 'SI', 'BA', 'MK', 'ME', 'XK'],
    north_america: ['US', 'CA', 'MX'],
    central_america: ['GT', 'BZ', 'SV', 'HN', 'NI', 'CR', 'PA'],
    caribbean: ['CU', 'JM', 'HT', 'DO', 'TT', 'BS', 'BB', 'AG', 'DM', 'LC', 'VC', 'GD', 'KN'],
    south_america: ['BR', 'AR', 'CO', 'PE', 'CL', 'VE', 'EC', 'BO', 'PY', 'UY', 'GY', 'SR'],
    north_africa: ['EG', 'MA', 'DZ', 'TN', 'LY', 'SD', 'MR'],
    west_africa: ['NG', 'GH', 'CI', 'ML', 'SN', 'BF', 'GN', 'SL', 'LR', 'GM', 'TG', 'BJ', 'NE', 'CV'],
    east_africa: ['ET', 'KE', 'TZ', 'UG', 'RW', 'BI', 'SO', 'DJ', 'ER', 'MW', 'MZ', 'ZM', 'ZW'],
    central_africa: ['CD', 'CG', 'GA', 'CM', 'TD', 'CF', 'GQ', 'ST'],
    southern_africa: ['ZA', 'NA', 'BW', 'SZ', 'LS', 'MG', 'MU', 'KM', 'SC'],
    oceania: ['AU', 'NZ', 'PG', 'FJ', 'SB', 'VU', 'WS', 'TO', 'KI', 'TV', 'NR', 'PW', 'MH', 'FM']
};

// 音乐风格分类
const STYLE_CATEGORIES = {
    traditional: ['chinese_traditional', 'japanese_traditional', 'korean_court', 'mongolian_pastoral'],
    folk: ['irish_celtic', 'bengali_folk', 'nepali_folk', 'philippine_ensemble'],
    classical: ['hindustani_classical', 'persian_classical', 'turkish_classical', 'vienna_classical'],
    modern: ['american_rock', 'british_rock', 'cosmopolitan_fusion'],
    rhythmic: ['brazilian_samba', 'nigerian_afrobeat', 'cuban_salsa', 'bulgarian_folk'],
    spiritual: ['ethiopian_jazz', 'zimbabwean_chimurenga', 'bhutanese_religious', 'malian_griot'],
    romantic: ['french_chanson', 'argentinian_tango', 'portuguese_fado'],
    desert: ['moroccan_gnawa', 'mauritanian_griots', 'nigerien_tuareg', 'libyan_folk'],
    tropical: ['indonesian_gamelan', 'caribbean_calypso', 'hawaiian', 'polynesian']
};

// 乐器库
const INSTRUMENT_LIBRARY = {
    // 弦乐器 Strings
    guzheng: { type: 'string', origin: 'CN', pitch: 'medium', timbre: 'plucked' },
    pipa: { type: 'string', origin: 'CN', pitch: 'medium', timbre: 'plucked' },
    erhu: { type: 'string', origin: 'CN', pitch: 'medium', timbre: 'bowed' },
    shamisen: { type: 'string', origin: 'JP', pitch: 'medium', timbre: 'plucked' },
    koto: { type: 'string', origin: 'JP', pitch: 'low', timbre: 'plucked' },
    sitar: { type: 'string', origin: 'IN', pitch: 'medium', timbre: 'plucked' },
    oud: { type: 'string', origin: 'ME', pitch: 'medium', timbre: 'plucked' },
    tar: { type: 'string', origin: 'IR', pitch: 'medium', timbre: 'plucked' },
    kora: { type: 'string', origin: 'AF', pitch: 'medium', timbre: 'plucked' },
    violin: { type: 'string', origin: 'EU', pitch: 'high', timbre: 'bowed' },
    guitar: { type: 'string', origin: 'ES', pitch: 'medium', timbre: 'plucked' },
    
    // 管乐器 Winds
    dizi: { type: 'wind', origin: 'CN', pitch: 'high', timbre: 'bright' },
    shakuhachi: { type: 'wind', origin: 'JP', pitch: 'low', timbre: 'breathy' },
    bansuri: { type: 'wind', origin: 'IN', pitch: 'medium', timbre: 'soft' },
    ney: { type: 'wind', origin: 'IR', pitch: 'medium', timbre: 'mellow' },
    quena: { type: 'wind', origin: 'PE', pitch: 'medium', timbre: 'penetrating' },
    didgeridoo: { type: 'wind', origin: 'AU', pitch: 'low', timbre: 'drone' },
    accordion: { type: 'wind', origin: 'EU', pitch: 'medium', timbre: 'reedy' },
    
    // 打击乐器 Percussion
    djembe: { type: 'percussion', origin: 'AF', pitch: 'low', timbre: 'deep' },
    tabla: { type: 'percussion', origin: 'IN', pitch: 'high', timbre: 'sharp' },
    taiko: { type: 'percussion', origin: 'JP', pitch: 'low', timbre: 'thunderous' },
    darbuka: { type: 'percussion', origin: 'ME', pitch: 'high', timbre: 'crisp' },
    congas: { type: 'percussion', origin: 'CU', pitch: 'medium', timbre: 'warm' },
    steelpan: { type: 'percussion', origin: 'TT', pitch: 'high', timbre: 'metallic' },
    gamelan: { type: 'percussion', origin: 'ID', pitch: 'high', timbre: 'metallic' },
    mbira: { type: 'percussion', origin: 'ZW', pitch: 'medium', timbre: 'twinkling' }
};

// 导出模块
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        COUNTRY_MUSIC,
        REGION_GROUPS,
        STYLE_CATEGORIES,
        INSTRUMENT_LIBRARY
    };
}
